team/urls.py
from django.conf.urls import patterns, url
from django.views.decorators.cache import cache_page

from team import views

urlpatterns = patterns('',
    url(r'^$', views.TeamListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^tournament_team/(?P<pk>\d+)/$', views.TournamentTeamDetailView.as_view(), name='tournamentteam_detail'),
    url(r'^competition_team/(?P<pk>\d+)/$', views.CompetitionTeamDetailView.as_view(), name='competitionteam_detail'),
    # url(r'^(?P<pk>\d+)/(?P<slug>[-_\w]+)/$', cache_page(60 * 15)(views.public_detail_team), name='detail'),
    # url(r'^(?P<pk>\d+)/(?P<slug>[-_\w]+)/(?P<edit_key>\w+)/$', views.private_detail_team, name='private_detail'),
    # url(r'^edit/(?P<team_id>\d+)/(?P<edit_key>\w+)/$', views.edit, name='edit'),
    # url(r'^register/$', views.register_team, name='register'),
    # url(r'^stats/$', views.stats, name='stats'),
    # url(r'^thanks/(?P<team_id>\d+)/$', views.thanks, name='thanks'),
    # url(r'^confirm_email/(?P<confirmation_key>\w+)/$', views.confirm_email, name='confirm_email'),
    # url(r'^ajax_historic_team/$', views.ajax_historic_team, name='ajax_historic_team'),
    # url(r'^ajax_historic_division/$', views.ajax_historic_division, name='ajax_historic_division'),
)

www/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

import autocomplete_light
autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^playtime/', include('playtime.urls')),
)


#favicon and robots.txt shut mail up patterns
urlpatterns += patterns('',
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/website/favicon.ico'))
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
  ) + urlpatterns


urlpatterns += patterns(
    '',
    url(r'^', include('cms.urls')),
)

team/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.core.exceptions import ValidationError

from www import settings
from member.models import Person
from django_countries.fields import CountryField
from cms.models.fields import PlaceholderField
import requests
import json

def my_report_slotname(instance):
    return 'tournament_report'

def my_competition_day1_slotname(instance):
    return 'competition_day1_report'

def my_competition_day2_slotname(instance):
    return 'competition_day2_report'

def my_competition_day3_slotname(instance):
    return 'competition_day3_report'

def my_competition_day4_slotname(instance):
    return 'competition_day4_report'

def my_team_slotname(instance):
    return 'team_description'


class Team(models.Model):
    name = models.CharField(max_length=100)
    roster = models.ManyToManyField(Person, through='TeamMember')
    description = PlaceholderField(my_team_slotname)


    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team:team_detail', args=[self.pk])


class TeamMember(models.Model):
    CAPTAIN = '1CA'
    PLAYER = '2PL'
    PRACTICE = '3PR'
    TRAINER = '4TR'
    COACH = '5CO'
    ALUMNI = '9AL'
    STATUS_CHOICES = (
        (CAPTAIN, 'captain'),
        (PLAYER, 'player'),
        (PRACTICE, 'practice only'),
        (TRAINER, 'trainer'),
        (COACH, 'coach'),
        (ALUMNI, 'alumni'),
    )
    STATUS_NAMES = dict((k,v) for k,v in STATUS_CHOICES)

    team = models.ForeignKey(Team)
    member = models.ForeignKey(Person)
    status = models.CharField(max_length=3,
                              choices=STATUS_CHOICES,
                              default=PLAYER)

    def __unicode__(self):
        return u'{1} ({0} of {2})'.format(self.STATUS_NAMES[self.status], self.member, self.team)

    class Meta:
        ordering = ['status', 'member__last_name']
        unique_together = ['team', 'member']


class Tournament(models.Model):
    GRASS = 'GR'
    BEACH = 'BE'
    INDOOR = 'IN'
    SURFACE_CHOICES = (
        (GRASS, 'grass'),
        (BEACH, 'beach'),
        (INDOOR, 'indoor'),
    )
    SURFACE_NAMES = dict((k,v) for k,v in SURFACE_CHOICES)


    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    number_teams = models.PositiveSmallIntegerField(null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    country = CountryField()
    link = models.URLField(null=True, blank=True)
    surface = models.CharField(max_length=2,
                              choices=SURFACE_CHOICES,
                              default=GRASS)

    team = models.ManyToManyField(Team, through='TournamentTeam')

    class Meta:
        ordering = ['start_date']

    def __unicode__(self):
        return self.name


class Competition(models.Model):
    OPEN = '1O'
    MIXED = '2M'
    WOMEN = '3W'
    DIVISION_CHOICES = (
        (OPEN, 'open'),
        (MIXED, 'mixed'),
        (WOMEN, 'women'),
    )
    div = models.CharField(max_length=2,
                           choices=DIVISION_CHOICES,
                           default=OPEN)

    number_divisions = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Number of Divisions')
    number_teams = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Number of Teams')

    day1 = models.DateField() # there should be at least one competition day
    day2 = models.DateField(blank=True, null=True)
    day3 = models.DateField(blank=True, null=True)
    day4 = models.DateField(blank=True, null=True)

    day1_lv_id = models.IntegerField(blank=True, null=True)
    day2_lv_id = models.IntegerField(blank=True, null=True)
    day3_lv_id = models.IntegerField(blank=True, null=True)
    day4_lv_id = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ['day1']

    def __unicode__(self):
        return u'{0} competition {1}'.format(self.get_div_display(), self.day1.year)

    @property
    def name(self):
        return self.__unicode__()

class CompetitionTeam(models.Model):
    team = models.ForeignKey(Team)
    competition = models.ForeignKey(Competition)
    competition_name = models.CharField(max_length=100,
                                        verbose_name='Competition Team Name',
                                        blank=True, null=True)

    seed = models.PositiveSmallIntegerField(null=True, blank=True)
    final_rank = models.PositiveSmallIntegerField(null=True, blank=True)
    spirit_rank = models.PositiveSmallIntegerField(null=True, blank=True)
    roster = models.ManyToManyField(Person, through='CompetitionTeamMember')

    report_day1 = PlaceholderField(my_competition_day1_slotname, related_name='report_day1')
    report_day2 = PlaceholderField(my_competition_day2_slotname, related_name='report_day2')
    report_day3 = PlaceholderField(my_competition_day3_slotname, related_name='report_day3')
    report_day4 = PlaceholderField(my_competition_day4_slotname, related_name='report_day4')


    def __unicode__(self):
        if self.competition_name:
            return u'{0} @{1}'.format(self.competition_name, self.competition)
        else:
            return u'{0} @{1}'.format(self.team, self.competition)

    def get_absolute_url(self):
        return reverse('team:competitionteam_detail', args=[self.pk])


    def import_team_roster(self):
        """
        if roster is of competition team is still empty
        copies team roster from team to this competitionteam
        """
        if self.roster.count() == 0:
            for team_member in self.team.teammember_set.all():
                if team_member.status != TeamMember.ALUMNI and team_member.status != TeamMember.PRACTICE:
                    competitionteam_member = CompetitionTeamMember(competitionteam=self,
                                                                   member=team_member.member,
                                                                   status=team_member.status)
                    competitionteam_member.save()
        return True

    def save(self, *args, **kwargs):
        first_time = not self.id
        super(CompetitionTeam, self).save(*args, **kwargs)
        if first_time:
            # import team roster by default
            self.import_team_roster()


class TournamentTeam(models.Model):
    OPEN = '1O'
    MIXED = '2M'
    WOMEN = '3W'
    DIVISION_CHOICES = (
        (OPEN, 'open'),
        (MIXED, 'mixed'),
        (WOMEN, 'women'),
    )

    team = models.ForeignKey(Team)
    tournament = models.ForeignKey(Tournament)
    div = models.CharField(max_length=2,
                           choices=DIVISION_CHOICES,
                           default=OPEN)

    seed = models.PositiveSmallIntegerField(null=True, blank=True)
    final_rank = models.PositiveSmallIntegerField(null=True, blank=True)
    spirit_rank = models.PositiveSmallIntegerField(null=True, blank=True)
    roster = models.ManyToManyField(Person, through='TournamentTeamMember')

    report = PlaceholderField(my_report_slotname)


    def __unicode__(self):
        return u'{0} @{1}'.format(self.team, self.tournament)

    def get_absolute_url(self):
        return reverse('team:tournamentteam_detail', args=[self.pk])

    def import_team_roster(self):
        """
        if roster is of competition team is still empty
        copies team roster from team to this competitionteam
        """
        if self.roster.count() == 0:
            for team_member in self.team.teammember_set.all():
                if team_member.status != TeamMember.ALUMNI and team_member.status != TeamMember.PRACTICE:
                    tournament_team = TournamentTeamMember(tournamentteam=self,
                                                           member=team_member.member,
                                                           status=team_member.status)
                    tournament_team.save()
        return True

    def save(self, *args, **kwargs):
        first_time = not self.id
        super(TournamentTeam, self).save(*args, **kwargs)
        if first_time:
            # import team roster by default
            self.import_team_roster()


class TournamentTeamMember(models.Model):
    CAPTAIN = '1CA'
    PLAYER = '2PL'
    PRACTICE = '3PR'
    TRAINER = '4TR'
    COACH = '5CO'
    STATUS_CHOICES = (
        (CAPTAIN, 'captain'),
        (PLAYER, 'player'),
        (PRACTICE, 'practice only'),
        (TRAINER, 'trainer'),
        (COACH, 'coach'),
    )
    STATUS_NAMES = dict((k,v) for k,v in STATUS_CHOICES)

    tournamentteam = models.ForeignKey(TournamentTeam)
    member = models.ForeignKey(Person)

    status = models.CharField(max_length=3,
                              choices=STATUS_CHOICES,
                              default=PLAYER)

    def __unicode__(self):
        return u'{1} ({0} of {2})'.format(self.STATUS_NAMES[self.status], self.member, self.tournamentteam)

    class Meta:
        ordering = ['status', 'member__last_name']
        unique_together = ['tournamentteam', 'member']


class CompetitionTeamMember(models.Model):
    CAPTAIN = '1CA'
    PLAYER = '2PL'
    PRACTICE = '3PR'
    TRAINER = '4TR'
    COACH = '5CO'
    STATUS_CHOICES = (
        (CAPTAIN, 'captain'),
        (PLAYER, 'player'),
        (PRACTICE, 'practice only'),
        (TRAINER, 'trainer'),
        (COACH, 'coach'),
    )
    STATUS_NAMES = dict((k,v) for k,v in STATUS_CHOICES)

    competitionteam = models.ForeignKey(CompetitionTeam)
    member = models.ForeignKey(Person)

    status = models.CharField(max_length=3,
                              choices=STATUS_CHOICES,
                              default=PLAYER)

    def __unicode__(self):
        return u'{1} ({0} of {2})'.format(self.STATUS_NAMES[self.status], self.member, self.competitionteam)

    class Meta:

team/views.py
from django.views.generic import ListView, DetailView

from team.models import Team, TournamentTeam, CompetitionTeam

class TeamListView(ListView):
    model = Team

    # def get_context_data(self, **kwargs):
    #     context = super(PredictionListView, self).get_context_data(**kwargs)
    #     context['averages'] = Prediction.objects.averages()
    #     context['num_predictions'] = Prediction.objects.all().count()
    #     return context

class TeamDetailView(DetailView):
    model = Team


class TournamentTeamDetailView(DetailView):
    model = TournamentTeam


class CompetitionTeamDetailView(DetailView):
    model = CompetitionTeam

team/templates/team/competitionteam_detail.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8">
        {% render_model_block object %}
        <h1>{{ instance.team.name }} @{{ instance.competition }}</h1>
        <div class="results">
            Seed: {{ instance.seed }} / {{ instance.competition.number_teams }}<br>
            Final Rank: {{ instance.final_rank }} / {{ instance.competition.number_teams }}<br>
            Spirit Rank: {{ instance.spirit_rank }} / {{ instance.competition.number_teams }}<br>
        </div>
        {% endrender_model_block %}

        <h2>Roster</h2>
        {% for competitionteammember in object.competitionteammember_set.all %}
            <div class="player">
                {% render_model_block competitionteammember %}
                    <span class="label label-default">{{ instance.get_status_display }}</span>
                    {% with instance.member as person %}
                        {% include 'member/person_detail_fragment.html' %}
                    {% endwith %}
                {% endrender_model_block %}
            </div>
        {% endfor %}

        <h2>Report</h2>
        {% render_placeholder object.report_day1 %}
        {% render_placeholder object.report_day2 %}
        {% render_placeholder object.report_day3 %}
        {% render_placeholder object.report_day4 %}
    </div>

  </div>

{% endblock %}

team/templates/team/team_detail.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8">
        {% render_model_block object %}
        <h1>Team: {{ instance.name }}</h1>
        {% endrender_model_block %}

        <h2>Roster</h2>
        {% for teammember in object.teammember_set.all %}
            <div class="player">
                {% render_model_block teammember %}
                    <span class="label label-default">{{ instance.get_status_display }}</span>
                    {% with instance.member as person %}
                        {% include 'member/person_detail_fragment.html' %}
                    {% endwith %}
                {% endrender_model_block %}
            </div>
        {% endfor %}

        {% if object.tournamentteam_set.all %}
            <h2>Tournament{{ object.tournamentteam_set.count|pluralize }}</h2>
            {% for tournamentteam in object.tournamentteam_set.all %}
                <div class="tournament">
                    {% render_model_block tournamentteam %}
                    {{ instance.tournament.start_date }} -
                        <a href="{% url 'team:tournamentteam_detail' instance.pk %}">{{ instance.tournament.name }}</a>,
                        in {{ instance.tournament.city }} {{ instance.tournament.country.name }}
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}

        {% if object.competitionteam_set.all %}
            <h2>Dutch Competition{{ object.competitionteam_set.count|pluralize }}</h2>
            {% for competitionteam in object.competitionteam_set.all %}
                <div class="competition">
                    {% render_model_block competitionteam %}
                        {{ instance.competition.day1 }}
                        <a href="{% url 'team:competitionteam_detail' instance.pk %}">{{ instance.competition }}</a>
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}

        <h2>Description</h2>
        {% render_placeholder object.description %}

    </div>

  </div>

{% endblock %}

team/templates/team/team_list.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8 neat-images cms-content">
        {% static_placeholder general_content %}
    </div>

    </div>
    <div class="row">
      <div class="col-md-8">
            <h1>Teams</h1>
        <ul>
        {% for team in object_list %}
            <li><a href="{% url 'team:team_detail' team.id %}">{{ team.name }}</a></li>
        {% empty %}
            <li>No teams yet.</li>
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="col-md-4 neat-images ww-sidebar">
        {% static_placeholder side_content %}
    </div>
  </div>

{% endblock %}

team/templates/team/thanks_signup.html
{% extends 'prediction/base_prediction.html' %}

{% block section_content %}

    <h1>Thanks for your prediction!</h1>

    <p>
    We have sent you an email with a secret edit link to update your prediction.
    </p>


{% endblock %}

team/templates/team/tournamentteam_detail.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8">
        {% render_model_block object %}
        <h1>{{ instance.team.name }} @{{ instance.tournament.name }}</h1>
        <div class="results">
            Seed: {{ instance.seed }} / {{ instance.tournament.number_teams }}<br>
            Final Rank: {{ instance.final_rank }} / {{ instance.tournament.number_teams }}<br>
            Spirit Rank: {{ instance.spirit_rank }} / {{ instance.tournament.number_teams }}<br>
        </div>
        {% endrender_model_block %}

        <h2>Roster</h2>
        {% for tournamentteammember in object.tournamentteammember_set.all %}
            <div class="player">
                {% render_model_block tournamentteammember %}
                    <span class="label label-default">{{ instance.get_status_display }}</span>
                    {% with instance.member as person %}
                        {% include 'member/person_detail_fragment.html' %}
                    {% endwith %}
                {% endrender_model_block %}
            </div>
        {% endfor %}

        <h2>Report</h2>
        {% render_placeholder object.report %}
    </div>

  </div>

{% endblock %}