member/urls.py
from django.conf.urls import patterns, url
from django.views.decorators.cache import cache_page

from member import views

urlpatterns = patterns('',
    url(r'^$', views.PersonListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.PersonDetailView.as_view(), name='detail'),
    url(r'^me/$', views.my_detail, name='my_detail'),
    # url(r'^(?P<pk>\d+)/(?P<slug>[-_\w]+)/$', cache_page(60 * 15)(views.public_detail_team), name='detail'),
    # url(r'^(?P<pk>\d+)/(?P<slug>[-_\w]+)/(?P<edit_key>\w+)/$', views.private_detail_team, name='private_detail'),
    # url(r'^edit/(?P<team_id>\d+)/(?P<edit_key>\w+)/$', views.edit, name='edit'),
    # url(r'^register/$', views.register_team, name='register'),
    # url(r'^stats/$', views.stats, name='stats'),
    # url(r'^thanks/(?P<team_id>\d+)/$', views.thanks, name='thanks'),
    # url(r'^confirm_email/(?P<confirmation_key>\w+)/$', views.confirm_email, name='confirm_email'),
    # url(r'^ajax_historic_team/$', views.ajax_historic_team, name='ajax_historic_team'),
    # url(r'^ajax_historic_division/$', views.ajax_historic_division, name='ajax_historic_division'),
)

www/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

import autocomplete_light
autocomplete_light.autodiscover()
admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^playtime/', include('playtime.urls')),
)


#favicon and robots.txt shut mail up patterns
urlpatterns += patterns('',
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/website/favicon.ico'))
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
  ) + urlpatterns


urlpatterns += patterns(
    '',
    url(r'^', include('cms.urls')),
)

member/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from django_iban.fields import IBANField, SWIFTBICField
from cms.models.fields import PlaceholderField
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
from django_countries.fields import CountryField
import hashlib

def my_member_slotname(instance):
    return 'member_description'

User.profile = property(lambda u: Person.objects.get_or_create(user=u)[0])


class Job(models.Model):
    description = models.CharField(max_length=50)
    bestuur = models.BooleanField(default=False)

    def __unicode__(self):
        return self.description


class Person(models.Model):
    MALE = '1M'
    FEMALE = '2F'
    GENDER_CHOICE = (
        (MALE, u'male'),
        (FEMALE, u'female'),
    )

    DONTKNOW = '1DN'
    BEGINNER = '2BG'
    INTERMEDIATE = '3IN'
    HIGH = '4HI'
    LEVEL_CHOICE = (
        (DONTKNOW, u"I don't know"),
        (BEGINNER, u'beginner'),
        (INTERMEDIATE, u'intermediate'),
        (HIGH, u'as high as possible'),
    )

    AGREE = '1OK'
    NOTAGREE = '2NO'
    AUTHORISATION_CHOICE = (
        (AGREE, u'I agree'),
        (NOTAGREE, u'I do not agree'),
    )

    NODISCOUNT = '1NO'
    STUDENT = '2ST'
    YOUTH = '3YO'
    DISCOUNT_CHOICE = (
        (NODISCOUNT, u'no discount'),
        (STUDENT, u'full-time student (not PhD/AiO)'),
        (YOUTH, u'youth'),
    )

    first_name = models.CharField(max_length=100)
    preposition = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=100)

    gender = models.CharField(max_length=2,
                              choices=GENDER_CHOICE,
                              default=MALE)
    playing_level = models.CharField(max_length=3,
                                     choices=LEVEL_CHOICE,
                                     default=DONTKNOW)
    street = models.CharField(max_length=200, blank=True, null=True)
    house_number = models.PositiveSmallIntegerField(blank=True, null=True)
    house_number_extension = models.CharField(max_length=20, blank=True, null=True)
    zip_code = models.CharField(max_length=7, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=40, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    citizenship = CountryField(blank=True, null=True)

    other_club = models.CharField(max_length=100, null=True, blank=True)
    nfb_membership = models.NullBooleanField(null=True, blank=True, verbose_name='pay NFB membership through Crunch?', default=None)

    discount = models.CharField(max_length=3,
                                  choices=DISCOUNT_CHOICE,
                                  default=NODISCOUNT)
    iban_authorisation = models.CharField(max_length=3,
                                          choices=AUTHORISATION_CHOICE,
                                          default=AGREE)
    iban = IBANField(blank=True, null=True)
    account_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='bank account in the name of')
    jobs = models.ManyToManyField(Job, through='MemberJob')

    email = models.EmailField(blank=True, null=True)

    user = models.OneToOneField(User, related_name='profile', blank=True, null=True)

    description = PlaceholderField(my_member_slotname)

    def __unicode__(self):
        if self.preposition:
            full_name = u'{0} {1} {2}'.format(self.first_name, self.preposition, self.last_name)
        else:
            full_name = u'{0} {1}'.format(self.first_name, self.last_name)
        return full_name

    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False

    class Meta:
        ordering = ['last_name']

    def get_absolute_url(self):
        return reverse('member:detail', args=[self.pk])


    def profile_image_url(self):
        fb_uid = SocialAccount.objects.filter(user_id=self.user.id, provider='facebook')

        if len(fb_uid):
            return "http://graph.facebook.com/{}/picture?width=40&height=40".format(fb_uid[0].uid)

        return "http://www.gravatar.com/avatar/{}?s=40".format(hashlib.md5(self.user.email).hexdigest())


    def clean(self):
        # an answer to nfb_membership must be specified if and only if other club is filled
        if self.other_club is not None and self.other_club != u'' and self.nfb_membership is None:
            raise ValidationError('If person is member of another club, you have to specify if NFB membership is payed through Crunch.')
        if self.other_club is None and self.nfb_membership is not None:
            raise ValidationError('If person is not member of another club, you have to leave NFB membership field blank.')



class MemberJob(models.Model):
    # PLAYER = '1PL'
    # CHAIRMAN = '2CH'
    # TREASURER = '3TR'
    # SECRETARY = '4SE'
    # COMPETITION = '5CO'
    # GENERAL = '6GE'
    # YOUTH = '7YO'
    # ALUMNI = '99A'
    # JOB_CHOICE = (
    #     (PLAYER, u'active player'),
    #     (CHAIRMAN, u'chairman (bestuur)'),
    #     (TREASURER, u'treasurer (bestuur)'),
    #     (SECRETARY, u'secretary (bestuur)'),
    #     (COMPETITION, u'competition officer (bestuur)'),
    #     (GENERAL, u'general board member (bestuur)'),
    #     (YOUTH, u'youth coordinator (bestuur)'),
    #     (ALUMNI, u'alumni'),
    # )
    job = models.ForeignKey(Job)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    person = models.ForeignKey(Person)

    def __unicode__(self):
        return self.job.description

member/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect

from member.models import Person, MemberJob

class PersonListView(ListView):
    model = Person


class PersonDetailView(DetailView):
    model = Person


def my_detail(request):
    if request.user.is_authenticated and hasattr(request.user, 'profile'):
        return redirect('member:detail', pk=request.user.profile.pk)
    else:
        return redirect('member:list')

member/templates/member/person_detail.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8">
        {% render_model_block object %}
        <h1>Member:
            {% with person=instance %}
            {% include 'member/person_detail_fragment.html' %}
            {% endwith %}
        </h1>
        {% endrender_model_block %}

        {% if object.jobs.all %}
            <h2>Jobs</h2>
            {% for job in object.jobs.all %}
                <div class="job">
                    {% render_model_block job %}
                    {{ instance.get_job_display }}: {{ instance.start_date }} - {{ instance.end_date }}
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}

        {% if object.teammember_set.all %}
            <h2>Teams</h2>
            {% for teammember in object.teammember_set.all %}
                <div class="team">
                    {% render_model_block teammember %}
                        {{ instance.get_status_display }} of
                        <a href="{% url 'team:team_detail' instance.team.pk %}">{{ instance.team.name }}</a>
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}

        {% if object.tournamentteam_set.all %}
            <h2>Tournaments</h2>
            {% for tournamentteam in object.tournamentteam_set.all %}
                <div class="tournament">
                    {% render_model_block tournamentteam %}
                    {{ instance.tournament.start_date }} -
                        <a href="{% url 'team:tournamentteam_detail' instance.pk %}">{{ instance.tournament.name }}</a>,
                        in {{ instance.tournament.city }} {{ instance.tournament.country.name }}
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}

        {% if object.competitionteam_set.all %}
            <h2>Competitions</h2>
            {% for competitionteam in object.competitionteam_set.all %}
                <div class="competition">
                    {% render_model_block competitionteam %}
                        <a href="{% url 'team:competitionteam_detail' instance.pk %}">{{ instance }}</a>
                    {% endrender_model_block %}
                </div>
            {% endfor %}
        {% endif %}


        <h2>Description</h2>
        {% render_placeholder object.description %}

    </div>

  </div>

{% endblock %}

member/templates/member/person_detail_fragment.html
{% if user.is_authenticated %}
    <a href="{% url 'member:detail' person.id %}">
    {{ person.first_name }} {{ person.last_name }}</a>
{% else %}
    {{ person.first_name }}
{% endif %}

member/templates/member/person_list.html
{% extends 'base_section.html' %}
{% load cms_tags sekizai_tags %}
{% load static %}
{% load bootstrap %}

{% block section_content %}

  <div class="row">
    <div class="col-md-8 neat-images cms-content">
        {% placeholder general_content %}
    </div>

    </div>
    <div class="row">
      <div class="col-md-8">
            <h1>People</h1>
        <ul>
        {% for person in object_list %}
            <li><a href="{% url 'member:detail' person.id %}">{{ person.first_name }}
            {% if user.is_authenticated %}{{ person.last_name }}{% endif %}</a></li>
        {% empty %}
            <li>No people yet.</li>
        {% endfor %}
        </ul>
      </div>
    </div>

{#    <div class="col-md-4 neat-images ww-sidebar">#}
{#        {% placeholder side_content %}#}
{#    </div>#}
  </div>

{% endblock %}